stages:
  - sonarqube-check
  - develop
  - V2.1

variables:
  GIT_CLEAN_FLAGS: none

sonarqube-check:
  stage: sonarqube-check
  tags:
    - sonarqube-check
  script: 
    - sonar-scanner -Dsonar.projectKey=sicnu_sicnu_data_cockpit_AYyBU56Z3Iv7fQhy86uh
  allow_failure: true
  only:
    - develop

develop:
  stage: develop 
  only:
    - develop
    - V2.1
  tags:
    - golive-test
  script:
    - if [ ! -d "/home/wwwroot/$CI_PROJECT_NAME" ];then ln -s $CI_PROJECT_DIR /home/wwwroot; echo "目录已创建！"; else echo "目录已存在！";fi
